-- =====================================================================
--  CourseApp - Schema (chuẩn PostgreSQL, chạy trên H2 MODE=PostgreSQL)
--  Spring Boot tự chạy file này khi khởi động (spring.sql.init).
-- =====================================================================

DROP TABLE IF EXISTS quiz_attempt_answers CASCADE;
DROP TABLE IF EXISTS quiz_attempts        CASCADE;
DROP TABLE IF EXISTS lesson_progress      CASCADE;
DROP TABLE IF EXISTS question_options     CASCADE;
DROP TABLE IF EXISTS questions            CASCADE;
DROP TABLE IF EXISTS lessons              CASCADE;
DROP TABLE IF EXISTS enrollments          CASCADE;
DROP TABLE IF EXISTS courses              CASCADE;
DROP TABLE IF EXISTS users                CASCADE;

-- 1. Người dùng
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(100) NOT NULL,
    email          VARCHAR(150) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL DEFAULT 'STUDENT',
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_role CHECK (role IN ('STUDENT', 'INSTRUCTOR', 'ADMIN'))
);

-- 2. Khóa học  (GET /api/courses)
CREATE TABLE courses (
    id             VARCHAR(50)  PRIMARY KEY,
    title          VARCHAR(200) NOT NULL,
    description    TEXT,
    thumbnail_url  VARCHAR(500),
    instructor_id  BIGINT,
    is_published   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_course_instructor FOREIGN KEY (instructor_id) REFERENCES users (id) ON DELETE SET NULL
);

-- 3. Ghi danh khóa học
CREATE TABLE enrollments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    course_id     VARCHAR(50) NOT NULL,
    enrolled_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at  TIMESTAMP,
    CONSTRAINT uq_enrollment UNIQUE (user_id, course_id),
    CONSTRAINT fk_enroll_user   FOREIGN KEY (user_id)   REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_enroll_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

-- 4. Bài học  (GET /api/courses/{courseId}/lessons)
CREATE TABLE lessons (
    id              VARCHAR(50)  PRIMARY KEY,
    course_id       VARCHAR(50)  NOT NULL,
    title           VARCHAR(200) NOT NULL,
    video_url       VARCHAR(500) NOT NULL,
    order_index     INTEGER      NOT NULL,
    pass_threshold  INTEGER      NOT NULL DEFAULT 75,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_lesson_order UNIQUE (course_id, order_index),
    CONSTRAINT chk_pass_threshold CHECK (pass_threshold BETWEEN 0 AND 100),
    CONSTRAINT fk_lesson_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

-- 5. Câu hỏi trắc nghiệm
CREATE TABLE questions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id    VARCHAR(50) NOT NULL,
    content      TEXT        NOT NULL,
    order_index  INTEGER     NOT NULL,
    CONSTRAINT uq_question_order UNIQUE (lesson_id, order_index),
    CONSTRAINT fk_question_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

-- 6. Đáp án (option_index = vị trí trong mảng options ở FE)
CREATE TABLE question_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT       NOT NULL,
    option_index  INTEGER      NOT NULL,
    content       VARCHAR(500) NOT NULL,
    is_correct    BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_option_index UNIQUE (question_id, option_index),
    CONSTRAINT fk_option_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);

-- 7. Tiến độ học theo user + bài học
CREATE TABLE lesson_progress (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    lesson_id         VARCHAR(50) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'LOCKED',
    video_watched     BOOLEAN     NOT NULL DEFAULT FALSE,
    video_watched_at  TIMESTAMP,
    quiz_passed       BOOLEAN     NOT NULL DEFAULT FALSE,
    best_score        INTEGER,
    unlocked_at       TIMESTAMP,
    completed_at      TIMESTAMP,
    updated_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_progress UNIQUE (user_id, lesson_id),
    CONSTRAINT chk_progress_status CHECK (status IN ('LOCKED', 'UNLOCKED', 'COMPLETED')),
    CONSTRAINT fk_progress_user   FOREIGN KEY (user_id)   REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_progress_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

-- 8. Lượt nộp bài quiz
CREATE TABLE quiz_attempts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    lesson_id         VARCHAR(50) NOT NULL,
    score_percentage  INTEGER     NOT NULL,
    correct_count     INTEGER     NOT NULL,
    total_questions   INTEGER     NOT NULL,
    is_passed         BOOLEAN     NOT NULL,
    submitted_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attempt_user   FOREIGN KEY (user_id)   REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_attempt_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);
CREATE INDEX idx_attempt_user_lesson ON quiz_attempts (user_id, lesson_id);

-- 9. Chi tiết câu trả lời của mỗi lượt nộp
CREATE TABLE quiz_attempt_answers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          BIGINT  NOT NULL,
    question_id         BIGINT  NOT NULL,
    selected_option_id  BIGINT,
    is_correct          BOOLEAN NOT NULL,
    CONSTRAINT uq_attempt_question UNIQUE (attempt_id, question_id),
    CONSTRAINT fk_answer_attempt  FOREIGN KEY (attempt_id)         REFERENCES quiz_attempts (id)    ON DELETE CASCADE,
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id)        REFERENCES questions (id)        ON DELETE CASCADE,
    CONSTRAINT fk_answer_option   FOREIGN KEY (selected_option_id) REFERENCES question_options (id) ON DELETE SET NULL
);
